databaseName: hackathon-proxy

dataSources:
  mariadb-hackathon:
    url: jdbc:mariadb://mariadb:3306/hackathon?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Taipei&allowMultiQueries=true
    username: shardingsphere_proxy
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1

rules:
  - !SHARDING
    tables:
      #      employee:
      #        actualDataNodes: mariadb-hackathon.employee
      #        tableStrategy:
      #          standard:
      #            shardingColumn: roc_id
      #            shardingAlgorithmName: database_inline
      skill:
        actualDataNodes: mariadb-hackathon.skill
        tableStrategy:
          standard:
            shardingColumn: name
            shardingAlgorithmName: database_inline
      team:
        actualDataNodes: mariadb-hackathon.team
        tableStrategy:
          standard:
            shardingColumn: name
            shardingAlgorithmName: database_inline
      vacancy:
        actualDataNodes: mariadb-hackathon.vacancy
        tableStrategy:
          standard:
            shardingColumn: title
            shardingAlgorithmName: database_inline
      resume:
        actualDataNodes: mariadb-hackathon.resume
        tableStrategy:
          standard:
            shardingColumn: file_name
            shardingAlgorithmName: database_inline
      allowed_skill_mapping:
        actualDataNodes: mariadb-hackathon.allowed_skill_mapping
        tableStrategy:
          standard:
            shardingColumn: team_id
            shardingAlgorithmName: database_inline
    #    defaultDatabaseStrategy:
    #      standard:
    #        shardingColumn: id
    #        shardingAlgorithmName: database_inline
    #    defaultTableStrategy:
    #      none:
    shardingAlgorithms:
      database_inline:
        type: INLINE
        props:
          algorithm-expression: mariadb-hackathon
  - !ENCRYPT
    tables:
      employee:
        columns:
          roc_id:
            cipher:
              name: roc_id
              encryptorName: aes_encryptor
    encryptors:
      aes_encryptor:
        type: CUSTOM_AES
        props:
          aes-key-value: 1234567890123456
