spring:
  main:
    banner-mode: off
  application:
    name: hackathon
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:hackathon:public
    username: sa
    password:
    driver-class-name: org.h2.Driver
  hikari:
    max-pool-size: 15
    min-idle: 15
  sql:
    init:
      schema-locations: classpath:h2/schema.sql
      data-locations: classpath:h2/data.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always