version: '3.8'
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000" # MinIO Console
      - "9001:9001" # MinIO API
    environment:
      MINIO_ROOT_USER: demo-user
      MINIO_ROOT_PASSWORD: demo-password
    command: server /data --console-address ":9001"
    volumes:
      - ./data:/data
      - ./config:/root/.minio
