spring:
  main:
    banner-mode: off
  application:
    name: springdatajpa
  datasource:
    url: jdbc:mariadb://localhost:3306/hackathon?useSSL=false&serverTimezone=Asia/Taipei&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: org.mariadb.jdbc.Driver
  hikari:
    max-pool-size: 15
    min-idle: 15
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false
        use_sql_comments: false

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

server:
  port: 8080

encrypt:
  employee:
    roc_id:
      aes-key-value: 1234567890123456