services:
  controller:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka-controller
    container_name: kafka-controller
    ports:
      - "9097:9097"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-controller:9097'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENERS: 'CONTROLLER://kafka-controller:9097'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT'
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    volumes:
      - kafka_controller_data:/var/lib/kafka/data

  broker1:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka-broker1
    container_name: kafka-broker1
    depends_on:
      - controller
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: 'broker'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-controller:9097'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka-broker1:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_LOG_DIRS: '/tmp/kraft-broker-logs'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
    volumes:
      - kafka_broker1_data:/tmp/kraft-broker-logs
    user: root

  broker2:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka-broker2
    container_name: kafka-broker2
    depends_on:
      - controller
    ports:
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: 'broker'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-controller:9097'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka-broker2:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9093'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_LOG_DIRS: '/tmp/kraft-broker-logs'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
    volumes:
      - kafka_broker2_data:/tmp/kraft-broker-logs
    user: root

  broker3:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka-broker3
    container_name: kafka-broker3
    depends_on:
      - controller
    ports:
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 4
      KAFKA_PROCESS_ROLES: 'broker'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-controller:9097'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka-broker3:9094'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9094'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_LOG_DIRS: '/tmp/kraft-broker-logs'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
    volumes:
      - kafka_broker3_data:/tmp/kraft-broker-logs
    user: root

  kafka-setup:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka-setup
    depends_on:
      - broker1
      - broker2
      - broker3
    entrypoint: >
      bash -c "
      echo 'Waiting for Kafka brokers to be ready...';
      sleep 30;
      echo 'Creating topic demo-topic...';
      kafka-topics --create --topic demo-topic --bootstrap-server kafka-broker1:9092 --replication-factor 1 --partitions 1;
      echo 'Creating user demo-user...';
      kafka-configs --bootstrap-server kafka-broker1:9092 --alter --add-config 'SCRAM-SHA-256=[password=demo-password]' --entity-type users --entity-name demo-user;
      echo 'Group ID: demo-group';
      "

volumes:
  kafka_controller_data:
    driver: local
  kafka_broker1_data:
    driver: local
  kafka_broker2_data:
    driver: local
  kafka_broker3_data:
    driver: local

