GET http://localhost:8082/api/employees

###
GET localhost:8082/api/employees/4

###
POST http://localhost:8082/api/employees
Content-Type: application/json
userName: test-user

{
  "name": "{{$random.name.name}}",
  "address": "{{$random.address.streetAddress}}",
  "gender":"{{$random.alphabetic(1)}}",
  "rocId":"{{$random.alphanumeric(10)}}"
}




