services:
  shardingsphere-proxy:
    image: apache/shardingsphere-proxy:latest
    container_name: shardingsphere-proxy
    restart: always
    ports:
      - "3307:3307"
    volumes:
      - ./ext-lib:/opt/shardingsphere-proxy/ext-lib
      - ./conf:/opt/shardingsphere-proxy/conf
    networks:
      - shared_network

networks:
  shared_network:
    external: true
