### Get all employees
GET http://localhost:8080/employee/
Accept: application/json

### Get employee by ID
GET http://localhost:8080/employee/
Accept: application/json

### Create a new employee
POST http://localhost:8080/employee/
Content-Type: application/json

{
  "name": "{{$random.name.name}}",
  "address": "{{$random.address.cityName}}",
  "gender": "male",
  "rocId": "{{$random.alphabetic(1)}}{{$random.alphabetic(9)}}"
}

### Update an employee
PUT http://localhost:8080/employee/1
Content-Type: application/json

{
  "name": "John Doe Updated",
  "address": "456 Second St, Taipei, Taiwan",
  "gender": "Male",
  "rocId": "A123456789"
}

### Delete an employee
DELETE http://localhost:8080/employee/1
Accept: application/json