@startuml
left to right direction
actor "API Client" as client
rectangle "DateTime Information System" {
  usecase "Print Current DateTime Information" as UC_PrintDateTime
}
client --> UC_PrintDateTime
@enduml
