@startuml
package "ShardingSphere Proxy Application" {
  [EmployeeController] <<component>> as WebTier
  [EmployeeMapper] <<component>> as DataAccessTier
}
WebTier ..> DataAccessTier : uses to paginate employees
@enduml
