@startuml
left to right direction
actor "API Client" as client
rectangle "Employee Management (via ShardingSphere Proxy)" {
  usecase "Get Employees With Pagination" as UC_GetPaginated
}
client --> UC_GetPaginated
@enduml
