@startuml
robust "Client" as Client
robust "EmployeeController (JPA)" as Controller
robust "EmployeeService" as Service

@0
Client is Idle
Controller is Idle
Service is Idle

@10
Client is Requesting
Controller is ReceivingRequest

@20
Controller is CallingService ' employeeService.findAll()
Service is ProcessingRequest

@40
Service is RespondingToController ' List<Employee>
Controller is ReceivingFromService

@50
Controller is RespondingToClient ' ResponseEntity<List<Employee>>
Client is ReceivingResponse

@60
Client is Idle
Controller is Idle
Service is Idle
@enduml
