@startuml
left to right direction
actor "API Client" as client
rectangle "Employee Management (via ShardingSphere Proxy)" {
  usecase "Get Employee By ID" as UC_GetById
}
client --> UC_GetById
@enduml
