@startuml
robust "Client" as Client
robust "EmployeeController (Proxy)" as Controller
robust "EmployeeMapper" as Mapper

@0
Client is Idle
Controller is Idle
Mapper is Idle

@10
Client is Requesting
Controller is ReceivingRequest

@20
Controller is CallingMapper ' employeeMapper.paginate(...)
Mapper is ProcessingRequest

@40
Mapper is RespondingToController ' Page<Employee>
Controller is ReceivingFromMapper

@50
Controller is RespondingToClient ' Page<Employee>
Client is ReceivingResponse

@60
Client is Idle
Controller is Idle
Mapper is Idle
@enduml
