@startuml
actor Client
participant "EmployeeController (JPA)" as EmployeeController
participant EmployeeService

Client -> EmployeeController: DELETE /employee/{id}
activate EmployeeController
EmployeeController -> EmployeeService: delete(id)
activate EmployeeService
EmployeeService --> EmployeeController: (void)
deactivate EmployeeService
EmployeeController -> EmployeeController: ResponseEntity.noContent().build()
EmployeeController --> Client: ResponseEntity<Void> (HTTP 204)
deactivate EmployeeController
@enduml
