@startuml
package com.finekuo.byshardingsphereproxy.controller {
  class EmployeeController {
    +deleteEmployee(id: Long): void
  }
}

package com.finekuo.mybatisflexcore.mapper {
  interface EmployeeMapper {
    +deleteById(id: Long): int ' or void
  }
}

com.finekuo.byshardingsphereproxy.controller.EmployeeController ..> com.finekuo.mybatisflexcore.mapper.EmployeeMapper : uses
@enduml
