@startuml
actor Client
participant "EmployeeController (JPA)" as EmployeeController
participant EmployeeService

Client -> EmployeeController: GET /employee
activate EmployeeController
EmployeeController -> EmployeeService: findAll()
activate EmployeeService
EmployeeService --> EmployeeController: List<Employee>
deactivate EmployeeService
EmployeeController -> EmployeeController: ResponseEntity.ok(list)
EmployeeController --> Client: ResponseEntity<List<Employee>>
deactivate EmployeeController
@enduml
