@startuml
actor Client
participant LoggingController

Client -> LoggingController: GET /logging/log?integer=X&string=Y
activate LoggingController
LoggingController -> LoggingController: new GetLogResponse()
LoggingController -> LoggingController: setInteger(integer)
LoggingController -> LoggingController: setString(string)
LoggingController -> LoggingController: setRocId("rocIdValue")
LoggingController -> LoggingController: setRoc_id("roc_id_value")
LoggingController -> LoggingController: setAccount_number("account_number_value")
LoggingController -> LoggingController: setCredit_card_number("credit_card_number_value")
LoggingController -> LoggingController: BaseResponse.success(response)
LoggingController --> Client: BaseResponse<GetLogResponse>
deactivate LoggingController
@enduml
