@startuml
robust "Client" as Client
robust "LoggingController" as Controller

@0
Client is Idle
Controller is Idle

@10
Client is Requesting
Controller is ReceivingRequest

@20
Controller is ProcessingRequest ' (new GetLogResponse(), set fields, BaseResponse.success())

@40
Controller is RespondingToClient
Client is ReceivingResponse

@50
Client is Idle
Controller is Idle
@enduml
