@startuml
actor Client
participant ResumeController
participant ResumeRepository
participant ResumeDTO

Client -> ResumeController: GET /resume/
activate ResumeController
ResumeController -> ResumeRepository: findAll()
activate ResumeRepository
ResumeRepository --> ResumeController: Iterable<Resume>
deactivate ResumeRepository
ResumeController -> ResumeDTO: fromEntity(resume) ' (repeated for each resume)
ResumeController -> ResumeController: new GetResumePayload(list<ResumeDTO>)
ResumeController -> ResumeController: BaseResponse.success(payload)
ResumeController --> Client: BaseResponse<GetResumePayload>
deactivate ResumeController
@enduml
