@startuml
robust "Client" as Client
robust "ResumeController" as Controller
robust "ResumeRepository" as Repository

@0
Client is Idle
Controller is Idle
Repository is Idle

@10
Client is Requesting
Controller is ReceivingRequest

@20
Controller is CallingRepository ' resumeRepository.findAll()
Repository is ProcessingRequest

@40
Repository is RespondingToController ' Iterable<Resume>
Controller is ReceivingFromRepository

@50
Controller is ProcessingResponse ' (map to DTOs, new GetResumePayload, BaseResponse.success)

@70
Controller is RespondingToClient ' BaseResponse<GetResumePayload>
Client is ReceivingResponse

@80
Client is Idle
Controller is Idle
Repository is Idle
@enduml
