@startuml
node "Application Server" {
  artifact "jpa-application.jar" {
    component SkillController
    component SkillService
  }
}
database "Database" {
  ' Represents the underlying database accessed by JPA
}
"Application Server" --> "Database" : (JPA access)
@enduml
