version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672" # AMQP port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: demo-user
      RABBITMQ_DEFAULT_PASS: demo-password
    volumes:
      - ./rabbitmq-config:/etc/rabbitmq
    command: >
      rabbitmq-server
