###
GET http://localhost:8080/employee
userName: test-user
account: employee

### Get employee by ID
GET http://localhost:8080/employee/2
userName: test-user
account: employee

### Create a new employee
POST http://localhost:8080/employee
Content-Type: application/json
userName: test-user

{
  "name": "{{$random.name.name}}",
  "address": "{{$random.address.streetAddress}}",
  "gender": "{{$random.alphabetic(1)}}",
  "rocId": "{{$random.alphanumeric(10)}}"
}

### Get employee by ID
GET http://localhost:8080/employee/mask/3
userName: test-user
account: employee

### Get employee by ID
GET http://localhost:8080/employee/mask/flattened/3
userName: test-user
account: employee