-- Create users (MariaDB already has root user from Docker setup)
-- CREATE USER IF NOT EXISTS 'pkuo'@'%' IDENTIFIED BY '123456';
-- GRANT ALL PRIVILEGES ON hackathon.* TO 'pkuo'@'%';
-- FLUSH PRIVILEGES;

-- Use the database
USE
hackathon;

-- Create tables
CREATE TABLE IF NOT EXISTS skill
(
  id
  BIGINT
  PRIMARY
  KEY
  AUTO_INCREMENT,
  name
  VARCHAR
(
  255
) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE =utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS team
(
  id
  BIGINT
  PRIMARY
  KEY
  AUTO_INCREMENT,
  name
  VARCHAR
(
  255
) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE =utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS vacancy
(
  id
  BIGINT
  PRIMARY
  KEY
  AUTO_INCREMENT,
  title
  VARCHAR
(
  255
) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE =utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS resume
(
  id
  BIGINT
  PRIMARY
  KEY
  AUTO_INCREMENT,
  file_name
  VARCHAR
(
  255
) NOT NULL,
  status INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE =utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS allowed_skill_mapping
(
  id
  BIGINT
  PRIMARY
  KEY
  AUTO_INCREMENT,
  team_id
  BIGINT
  NOT
  NULL,
  vacancy_id
  BIGINT
  NOT
  NULL,
  skill_id
  BIGINT
  NOT
  NULL,
  skill_level
  INT
  NOT
  NULL,
  created_at
  DATETIME
  NOT
  NULL
  DEFAULT
  CURRENT_TIMESTAMP,
  updated_at
  DATETIME
  NOT
  NULL
  DEFAULT
  CURRENT_TIMESTAMP
  ON
  UPDATE
  CURRENT_TIMESTAMP,
  UNIQUE
  KEY
  uk_team_skill_level
(
  team_id,
  skill_id,
  skill_level
),
  FOREIGN KEY
(
  team_id
) REFERENCES team
(
  id
),
  FOREIGN KEY
(
  vacancy_id
) REFERENCES vacancy
(
  id
),
  FOREIGN KEY
(
  skill_id
) REFERENCES skill
(
  id
)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE =utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS employee
(
  id
  BIGINT
  PRIMARY
  KEY
  AUTO_INCREMENT,
  name
  VARCHAR
(
  255
) NOT NULL,
  address VARCHAR
(
  255
) NOT NULL,
  gender VARCHAR
(
  50
) NOT NULL,
  roc_id VARCHAR
(
  255
) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE =utf8mb4_unicode_ci;
